### ISSUE TITLE
Dialogue Text Nightmare

### ISSUE THREAD

**Issue by ghost** [bbepis/BepisPlugins#11]
I am writing this, not because it currently is an issue with your translation plugin (although it probably is), but rather to share some information I gathered while playing around with my plugin.

I will use the following dialogue as an example:

「名残惜しいですわ……でも、そろそろ時間なので、失礼いたします」

Which I have no idea what means. :)

Basically, when the text is initially set on the text property of TMP_Text, the following happens:
 1. It sets the text to the exact string: 「名残惜しいですわ……でも、そろそろ時間なので、失礼いたします」
 2. As the text scrolls in, it will now set the text to various pieces of that string. Ugh. Individual strings such as:
   * 「名
   * 残惜
   * しい
   * ...  (which is really weird!)
 3. Once the text has fully scrolled in, it will set the text back to the original dialogue text, BUT if the string is longer than what can be on a line, additional newline characters and Japanese whitespace will be added. Also, in my experience, where that whitespace is placed is inconsistent. For instance: 「名残惜しいですわ……でも、そろそろ時間なので、失礼いた\n　します」

Also, when the text is later displayed if you scroll up (to display history), then the text that the textbox will be set to is the original string without newlines.

Which makes it rather difficult to provide an easy translating experience, as you might have to translate the exact same string in 2 or more ways.

The way I am solving this is in my plugin (which does not need to provide super exact translations!), is in the following way:
 * I populate the translation dictionary with keys both with and without newlines/whitespace.
 * I make two lookups in the dictionary, first the original string, then without newlines/whitespace.

This means that I will only populate the dictionary I create (and therefore also files I create) with one version of that same string, and that will happen all variations that may occur.

I do not know how these types of problems have been solved in previous translations. I am simply sharing my experience.

**Comment by leakim1336** [comment]
Just an addon to the above comment, the way that I handle the fact that the text constantly changes on the same UI component is by "debouncing" the translation until it does not change anymore.

**Comment by DarkPulse** [comment]
If there's a text display speed, setting it on fastest usually makes the line display instant. It's what we did in a few other Illusion eroge I worked on.
