### ISSUE TITLE
Dynamic Translation loader doesnt work with Auto Translator Plugin

### ISSUE THREAD

**Issue by Blulaz** [bbepis/BepisPlugins#14]
Seems like the latest version of auto translator (2.3.0) cant seem to work with the dynamictranslationloader plugin that came with the r3. game will just "crash" without any error prompt upon startup. can i get a confirmation on this?
i tried using the older version of dynamicTL (r2) and it works fine alongside with autotranslator 2.3.0

**Comment by b800047** [comment]
Upgrade to 2.5.0 autotranslators of your choosing and you'll be fine (BepIn or IPA)
