### ISSUE TITLE
Can ExtensibleSaveFormat handle ChaFileCoordinate?

### ISSUE THREAD

**Issue by WcLyic** [bbepis/BepisPlugins#16]
Not only ChaFile, i think ChaFileCoordinate also need to be handled for Sideloader to fix the wrong IDs.

**Comment by bbepis** [comment]
ChaFileCoordinate is planned. It's currently not implemented because it's a lot more complicated to keep track of (there's only one ChaFileBody, ChaFileFace and ChaFileHair per card, but there's 6 or 7 ChaFileCoordinate per save file)

**Comment by bbepis** [comment]
Completed in 81e235e and bf0086a

**Comment by WcLyic** [comment]
Not only the chara card, i also mean the coordinate card.
