### ISSUE TITLE
r4 Plugins Crashing my game

### ISSUE THREAD

**Issue by b800047** [bbepis/BepisPlugins#20]
To cut to the point, whatever changes there are to r4 plugins, seems to crash my game at startup. I'm having to downgrade to r3 plugins that give me no problems whatsoever. I'm on the latest update of the game (koikatu_02_plus_cdp05v25_all + sub) using additional mod plugins and using autotranslators. Here's the list of the ones I added:
0Harmony.dll
CheatTools.dll
Demosaic.dll
ExIn.dll
FPSCounter.dll
KoiSkinOverlay.dll
XUnity.AutoTranslator.Plugin.BepIn.dll
XUnity.AutoTranslator.Plugin.Core.dll
XUnity.AutoTranslator.Plugin.IPA.dll
AutoTranslatorConfig.ini (translator settings)
config.ini (plugin settings)
I even have a mod folder named "IPA" with both KK_HeadUtl.dll and KK_HeadUtl.ini used for first-person point-of-view. I have clothing mods but I don't think thats the case since none of them conflict with the game itself and are their own separate files. R3 was and still IS able to load and run everything smoothly, so whatver the issue please fix r4 or let me know what .dll and/or translators I should erase...by the way keep up the good work...
[R3 output_log.txt](https://github.com/bbepis/BepisPlugins/files/2063206/R3.output_log.txt)
[R4 output_log.txt](https://github.com/bbepis/BepisPlugins/files/2063207/R4.output_log.txt)
Got this on the on May 26, 2018 sorry if I haven't posted the files as I said
[error.log](https://github.com/bbepis/BepisPlugins/files/2063215/error.log)
[output_log.txt](https://github.com/bbepis/BepisPlugins/files/2063216/output_log.txt)
R3 still works on my computer fyi

Edit: sorry if i havent posted any updates on my end, it seems r4 does work, i was just missing the ExtensibleSaveFormat.dll...for some reason some people have reported in other forums not receiving it or not being in the download at all...but yeah sorry for the inconvinience and make sure to add a list or something to let you know what dlls you need or are missing...

**Comment by bbepis** [comment]
Hi,
Do you mind posting your Koikatu_Data\\output_log.txt?
It may have personal info in it so edit it out if it does

**Comment by b800047** [comment]
You're gonna have to wait until Monday, I posted this issue off of my phone...but I'll try to put the output logs of both r3 and r4 so you can compare and contrast

**Comment by ManlyMarco** [comment]
@b800047 Can you try clearing your BepInEx folder and downloading the new plugins again? You seem to have a bit of a mess in there (both Bepin and IPA versions of plugins).
