### ISSUE TITLE
manifest.xml suggestion: mod dependency, hard or soft

### ISSUE THREAD

**Issue by enkephalin07** [bbepis/BepisPlugins#28]
Declare a mod dependency by guid in the manifest so your mod won't load if the mod is missing. This would be helpful for both zipmods and plugins. For soft dependency you could declare which files to load or omit loading, and perhaps direct to a folder of files that only load as alternates.

**Comment by ManlyMarco** [comment]
So far it seems like there was low to no interest in this. If a plugin needs a zipmod then it can check if it exists easily enough. If a zipmod needs a plugin to work it usually will simply do nothing if loaded, so it's not really an issue.

I'm closing the issue for now, if there's interest it can be reopened later.
