### ISSUE TITLE
Some sideloader bugs

### ISSUE THREAD

**Issue by DeathWeasel1337** [bbepis/BepisPlugins#40]
Some item categories do not save with proper sideloader information. Saving a character with these and loading the character shows no UAR resolving, adding or removing any mod from the mods folder causes them to load incorrectly.
These are all the ones that do not save correctly:
- [x] Clothing Patterns
- [x] Emblems
- [x] Eye Gradient Type
- [x] Eyeshadow Type
- [x] Cheek Type
- [x] Lip Type
- [x] Face Paints

**Comment by DeathWeasel1337** [comment]
Some mods when converted to sideloader throw an error in the console and cause all sideloader items of that category to not display in the lists. This is the error message thrown by the sideloader conversion of yamadamod's shoesHM.

[Error] System.NullReferenceException: Object reference not set to an instance o
f an object
  at Sideloader.BundleManager.TryGetObjectFromName (System.String name, System.S
tring assetBundle, System.Type type, UnityEngine.Object& obj) [0x00000] in <file
name unknown>:0
  at Sideloader.Sideloader.RedirectHook (System.String assetBundleName, System.S
tring assetName, System.Type type, System.String manifestAssetBundleName, .Asset
BundleLoadAssetOperation& result) [0x00000] in <filename unknown>:0
  at ResourceRedirector.ResourceRedirector.HandleAsset (System.String assetBundl
eName, System.String assetName, System.Type type, System.String manifestAssetBun
dleName, .AssetBundleLoadAssetOperation& __result) [0x00000] in <filename unknow
n>:0
[Error] System.NullReferenceException: Object reference not set to an instance o
f an object
  at Sideloader.BundleManager.TryGetObjectFromName (System.String name, System.S
tring assetBundle, System.Type type, UnityEngine.Object& obj) [0x00000] in <file
name unknown>:0
  at Sideloader.Sideloader.RedirectHook (System.String assetBundleName, System.S
tring assetName, System.Type type, System.String manifestAssetBundleName, .Asset
BundleLoadAssetOperation& result) [0x00000] in <filename unknown>:0
  at ResourceRedirector.ResourceRedirector.HandleAsset (System.String assetBundl
eName, System.String assetName, System.Type type, System.String manifestAssetBun
dleName, .AssetBundleLoadAssetOperation& __result) [0x00000] in <filename unknow
n>:0

**Comment by DeathWeasel1337** [comment]
Two accessories that share a same ID but different accessory categories cause some problems with sideloader. For example, in the sideloader conversion of Roy12's schoolgirl pack A, the Hoop Earnings and Hoop Bracelet both have ID 80 but the Hoop Earrings disappear when loading the character. Console shows an attempt to resolve the ID:

[Info] [UAR] Resolving com.roy12.SexySchoolgirlPackA:outfit0.accessory0.ChaFileA
ccessory.PartsInfo.id from slot 80 to slot 100000623

Saving both the Earring and Bracelet and loading the character shows two apparently identical attempts to resolve the ID:

[Info] [UAR] Resolving com.roy12.SexySchoolgirlPackA:outfit0.accessory0.ChaFileA
ccessory.PartsInfo.id from slot 80 to slot 100000623
[Info] [UAR] Resolving com.roy12.SexySchoolgirlPackA:outfit0.accessory1.ChaFileA
ccessory.PartsInfo.id from slot 80 to slot 100000623

**Comment by DeathWeasel1337** [comment]
When attempting to load hard mod cards using sideloader mods by holding alt and pressing load, sometimes accessories don't load correctly. For example, the attached card has two hair accessories that make up her front hair but one loads and the other does not. Both accessories match the hard mod ID, both accessories are outside of vanilla range, and both are from the same mod.

![8e57daa24ee9f204112c819cac7703b4a20ee1c3](https://user-images.githubusercontent.com/37981563/42860875-27efe5c0-8a1e-11e8-9758-e77446adde63.png)

**Comment by DeathWeasel1337** [comment]
Sideloader information doesn't save to coordinate cards

**Comment by DeathWeasel1337** [comment]
Malformed manifest.xml files cause sideloader to stop loading mods. Ideally, it should throw a warning informing the mod maker of their mistake, skip that mod, and continue loading the rest.

**Comment by DeathWeasel1337** [comment]
During some events such as a girl greeting you on the way to school, no sideloader information is loaded for the character and they will appear totally without any of their modded clothes, hairs, accessories, etc.

**Comment by DeathWeasel1337** [comment]
Editing a scenario character and adding a sideloader item such as clothing causes the game to get stuck on a black screen when the character is supposed to appear in a cutscene.

**Comment by ezdiy** [comment]
If a zipmod is present for makeup, it ends up "infecting" the field so that it works only for that particular user - everyone else sees corrupted unresolvable id. This leads to a situation where only normal mods work for makeup, and zipmods are useless. Either don't rewrite makeups, or rewrite em properly.

**Comment by DeathWeasel1337** [comment]
Sideloader mods with .png files instead of .unity3d will not work unless they are in a folder that match an existing unity3d file. For example, putting .png files in abdata\chara\demon_skin_suntan will not work but putting the .png files in abdata\chara\mt_sunburn_00 will work because mt_sunburn_00.unity3d exists in the game files at that location.

**Comment by ManlyMarco** [comment]
I added checkboxes for all of the issues, please check everything that's fixed.

**Comment by ManlyMarco** [comment]
Everything is fixed with the latest PR, good work.
