### ISSUE TITLE
About two kinds of mod

### ISSUE THREAD

**Issue by wycstc353** [bbepis/BepisPlugins#47]
I'm an user of your BeplnEx,and I'm writing this message to you to present what l think on the further improvement of BeplnEx.I'd like to suggest that:If the author used  a zipmod(those  kind if mods placed in a document named mods ) to make his or her character card, even one have stored a same mod in different  form(that means he stored this mod in normal way as to place it in abdata) cannot load the card correctly. It's the same by the contrast.May I suggest that you make these two kinds of mods be employed universally.Please take good consideration of my advice,thanks.

**Comment by ManlyMarco** [comment]
If you save a card that uses mod versions for sideloader it should already do what you are describing. Make sure both sideloader mod and abdata mod are the same version and use the same IDs.
