### ISSUE TITLE
Sideloader mods not working properly in base game

### ISSUE THREAD

**Issue by AceofWind** [bbepis/BepisPlugins#51]
I've installed both 4.1 of BepInEx and r5.1 of the BepisPlugins. None of the sideloader mods will load in my game properly unless I launch the game through the patchwork launcher and I get a whole lot of missing mod errors when I go into Girl Selection in Free H Mode. I can still select and view them on the girls in the chara maker but can't load the outfits/accessories properly from the cards.

Edit: I tried reinstalling the game and doing a fresh reinstall of both BepInEx and the BepisPlugins, it didn't fix my issue.

Here's what it looks like in the console
![sideloader plugin bugs](https://user-images.githubusercontent.com/41172464/45572468-55620780-b837-11e8-850b-a44e332a3b76.png)

Operating System: Win 7 x64bit
GPU: GTX 970
Ram: 16gb DDR3
CPU: i5 4460

My Directories:
C:\illusion\Koikatu\mods\Sideloader Modpack\ (all the mod archives here have a .zipmod extension)
C:\illusion\Koikatu\BepInEx

I'm also using the latest patch for the game

**Comment by ManlyMarco** [comment]
Are you sure you actually have these mods? Download newest sideloader modpack and try again if you didn't already.

**Comment by AceofWind** [comment]
Okay I just tried it again. The game goes through a very long loading process and displays these messages in the console
![Uploading koikatsu missing mod.png…]()

**Comment by ManlyMarco** [comment]
Looks like these cards were saved with a bugged sideloader version. Sadly you'll have to manually fix these cards.

**Comment by AceofWind** [comment]
Thanks for the tip, I pinpointed the the culprit causing these problems to be a card of Eureka from Eureka 7
