### ISSUE TITLE
DTL crashes ADV (BepBE x.66 and Plugins Build _110)

### ISSUE THREAD

**Issue by enkephalin07** [bbepis/BepisPlugins#53]
Running with nothing but BE+Plugins, you can reach this error quickly through Title Menu->Extras->Events, and pick any one of them. ![2018-09-08 15_24_20-bepinex 4 1 0 66 - koikatu](https://user-images.githubusercontent.com/15174848/45258379-efc7d400-b37b-11e8-95a6-1fed12e31580.png)From there the game hangs on a white screen.
Output details:
[output_log.txt](https://github.com/bbepis/BepisPlugins/files/2363701/output_log.txt)

**Comment by ManlyMarco** [comment]
Seems to be resolved
