### ISSUE TITLE
suggestion: Screencap improvement with ability to capture semi-transparency pixels

### ISSUE THREAD

**Issue by Madevil** [bbepis/BepisPlugins#67]
may I suggest to include this feature when it capturing screenshot with alpha enabled? many thanks

![koikatsu-2018-10-06-16-54-46](https://user-images.githubusercontent.com/760597/46570946-286cc480-c99f-11e8-8f22-4bf65919ef1b.png)

**Comment by ManlyMarco** [comment]
Improved to some extent. Now transparent pixels are not black, but there is no partial transparency (so it's either fully opaque or fully transparent).

**Comment by ManlyMarco** [comment]
It should work better in recent versions. It's unlikely that it gets improved any more than this so I'm closing this issue.
