### ISSUE TITLE
XUnity AutoTranslator Compability

### ISSUE THREAD

**Issue by ghost** [bbepis/BepisPlugins#7]
Since you mentioned it on Hongfire, I thought I'd make an issue instead. Easier to track.

You mentioned:

"I can do what I did with my other plugins and set up an event/hook subscription where I fire an event for any line that's attempting to be translated, but can't doesn't have a translation. Your plugin would then be able to use that to return a translation, which would be completely conflict-proof since there's only one set of hooks."

There's a few issues here:
 1. My plugin requires the component that must be translated, not the text, as it functions asynchronously most of the time when it needs to translate a text. Of course, you could provide a callback, but things get messy quickly, and this wont work, because my plugin does some trickery in order to handle "story" mode texts (text that scrolls in and causes text change event constantly).
 3. My plugin REALLY does not want to take an external dependency on a component that depends on a specific game.

Now, how can we solve these issues?
 * I could implement a specialized version that takes a dependency on your plugin, but that would mean you would have to change your plugin to use components rather than texts. Or I could use reflection and attempt to find the event without taking a dependency. In this case I would stop hooking into the TextMeshPro and UGUI events. 
 * My plugin will in general only attempt translations on texts it finds that includes some form of Japanese characters, which should mean that if you are able to perform your translation before my plugin, mine will simply ignore them. Again, then I think the best approach would be for you to hook into the same events as my plugin. I have already added a [HarmonyAfter] attribute to my hooks, so you would automatically get first shot. This would probably not matter for the Prefixes you have added currently, but would matter for other events, that you would need to include also.

However, the one thing that annoys me the most is the following: When I change the text in my plugin, your plugin will then attempt to translate the translated text, which is not great (because it listens to changes in the text property). The only way for this to be resolved is for some form of coordination between the plugins. Or you could ignore texts that does not contain Japanese.

There's also the very real chance of a infinite loop if you hook into the text events in the same way as I do (by getting the component and setting the text property in your code). But only if your translated text actually contains Japanese characters, as mine would then also attempt to translate it, and set the text.

Now, enough problems. How do I suggest we solve this?

I can think of two solutions, that I like:

**SOLUTION 1**
 * You hook into the same text events as I do in order to translate the texts, and make sure you do it in the same way as you do now (by modifying the argument in a Prefix hook).
 * You should also hook into the Awake/OnEnabled method like I do for UGUI/TextMeshPro. In this case, you would have to call the setter on the text property, and while doing so, you would have to disable listening on your own hooks (otherwise you would handle your own setter!). However, I would get a callback, but since the text you provided contains no Japanese, I would ignore it.
 * You ignore texts that does not contain Japanese.
 * I would have to implement some sort shortcircuit, that ensures my plugin never interferes with other plugins that works the way mine those, in order to prevent an infinite loop or a StackOverflowException. This is fairly easy to do though, I would just need to add a flag to indicate whether or not I am currently setting a text on a component, and then not do anything if that is already set for that specific component. :)

Will the compability be perfect with this approach? No. There would still be problems with the "hotkeys" I have implemented to toggle between translated and untranslated. However, it would only mean that feature would not really work, as when I change my texts back to Japanese your plugin would attempt to translate them.

Is this too convoluted? Maybe it is.

I can also implement this if you are interested, it is actually fairly few changes, but I think they would go a long way.

**SOLUTION 2**
 * I take a **soft** dependency on your plugin. I will attempt to lookup a component that has your plugin type through reflection. You will expose an event as an Action<object, string> named something like "OnUnableToTranslate" where the object is the component that must be translated and the string is the text. Eg.  Text, TextMeshProUGUI, etc.. I will disable my hooks in case I find the event. You will have to include the text string, as the text has not been set on the component yet in a Prefix hook.
 * You ignore texts that does not contain Japanese. Again, otherwise you will handle my events when I set the text.
 * I would have to implement some sort shortcircuit, that ensures my plugin never interferes with other plugins that works the way mine those, in order to prevent an infinite loop or a StackOverflowException. This is fairly easy to do though, I would just need to add a flag to indicate whether or not I am currently setting a text on a component, and then not do anything if that is already set for that specific component. :)
 * In case you get "story text" that scrolls in, you can just spam the event. My plugin will handle that just fine.

What do you think?

**Comment by leakim1336** [comment]
After reading it, I actually think solution 2 is rather elegant.

**Comment by leakim1336** [comment]
To make a generic solution, I would like if it is possible if there was a hook for each available text framework that you use.

For instance, you could implement two events on DynamicTranslator:

public event Action<string, object> OnUnableToTranslateUGUI;
public event Action<string, object> OnUnableToTranslateTextMeshPro;

In this way, I can still handle IMGUI and NGUI text events, yeah? :)

**Comment by leakim1336** [comment]
I've implemented my part on this branch:

https://github.com/XUnity-Plugins/XUnity.AutoTranslator/tree/feature/plugin_integration

**Comment by leakim1336** [comment]
Hm. I am trying to create a pull request, but I am absolutely unable to build the solution, even after adding all the missing DLLs in the lib folder manually.

Do you use something special to build this project? I've tried with both VS2017 and VS2015.

**Comment by leakim1336** [comment]
Finally figured out what I was doing wrong. :) Testing it now.

**Comment by leakim1336** [comment]
Good news, everyone! I managed to make it work.

Two notes:
 * I had to do something fairly awkward though. I had to use an event with a return value, to handle the situation where I call SetText from my own plugin immediately, if it was cached up. This was caused by me then setting a translated text, and afterwards your plugin setting the untranslated text, because that method was called first. :) I could not think of any other way of solving this issue, if none of the two plugins has a references to eachother.
 * You should probably consider hooking into more of the text change events. If I use my plugin alone, it is better at figuring out what needs to be translated. Consider looking into which events I hook into.

I will see if I can make a pull request in a moment.
