### ISSUE TITLE
sideloaderテストビルドについて

### ISSUE THREAD

**Issue by nirvana358888** [bbepis/BepisPlugins#70]
最新のBepisPlugins_d6ca3aa_247を使用しhardmodで読み込めるか試しました。
結果アクセサリーの20個目までは問題なく読み込めました。
ただしMoreAccessoriesを使用して21個目以降は駄目でした。
作者が違うプラグインですし難しいかもしれませんが、対応出来ればお願いします。

**Comment by ManlyMarco** [comment]
Issue is discussed here: https://github.com/DeathWeasel1337/KK_Plugins/issues/2
