### ISSUE TITLE
Suggestion: ColorCorrector hotkey

### ISSUE THREAD

**Issue by wingfixer** [bbepis/BepisPlugins#74]
So, yeah. AmplifyColorEffect is also used for studio filters, unfortunately, so having to open the config menu and disable the plugin every time I want to use one is pretty inconvenient.

**Comment by ManlyMarco** [comment]
Are you fully up to date? This setting should not work at all in studio.

**Comment by wingfixer** [comment]
Fairly certain I am, yes. What do you mean by "this setting"? The filter has always been a thing in studio, and every studio filter is just the saturation filter + something else. Somehow even though there's the "SepiaTone" object, it's not actually used for the Sepia filter.
![ace](https://user-images.githubusercontent.com/42689235/58988000-66014600-87e9-11e9-977a-44dd7297912c.png)

**Comment by ManlyMarco** [comment]
I see what was going on. I completely disabled the plugin in studio since all settings can be changed from the interface.

44a7be811d08e937a323e3d707f506ef584df797

**Comment by wingfixer** [comment]
That's, uhhh... I'm not sure how I'm supposed to disable it otherwise. The "Flat Color" filter at 0 looks the closest but still not it, and "Midday" is oversaturated at any value.
