### ISSUE TITLE
ExtensibleSaveFormat cannot load game

### ISSUE THREAD

**Issue by leakim1336** [bbepis/BepisPlugins#9]
So, I started a game without any Bepis plugins. 

I saved.

I installed this mod.

I can no longer load the game.

No error in Developer console, button simply unresponsive.

Honestly, I do not really know what the mod does, but it comes in a bundle, so I thought it was worth sharing. :)

**Comment by bbepis** [comment]
This has been fixed in fb4f395, which I plan on releasing sometime later today.

@Blulaz Sideloader relies on extended save format. I haven't heard of that bug before, but I'll investigate it later today as well.

**Comment by Blulaz** [comment]
Okay thank you very much.

**Comment by bbepis** [comment]
@Blulaz I have fixed this in fb4f395.

**Comment by Blulaz** [comment]
erm, did you mean erm, did you mean [e59aa94](https://github.com/bbepis/BepisPlugins/commit/e59aa943226ef361cb849a068d2cae4a1dab4b80) ?
thank you for the good work, but i think i'll wait for the next public release just like everyone else

**Comment by bbepis** [comment]
Yes, that is what I meant to type. I'll go ahead and close this issue then.
